server:
  ip: 127.0.0.1
  port: ${PORT:8084}

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  flyway:
    enabled: true
    schemas: REGISTRAR
    validate-on-migrate: true

---

spring:
  profiles: docker

security:
  oauth2:
    resource:
      userInfoUri: http://security-service:9999/uaa/user
